[package]
name = "utxo-oracle"
version = "0.1.0"
authors = ["Devrandom <miron@basezero.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.7.0"
bitcoin = "0.21.0"
